#!/usr/bin/env wolframscript
(* ::Package:: *)

(* ::Section:: *)
(*Problem 7: 10001st prime*)


(* ::Text:: *)
(*By listing the first six prime numbers : 2, 3, 5, 7, 11, and 13, we can see that the 6 th prime is 13.*)
(**)
(*What is the 10 001 st prime number?  *)


(* ::Text:: *)
(*Mean timing: 0.0003125 ms*)


(* ::Input::Initialization:: *)
Print@Prime[10001]


(* ::Text:: *)
(*Obfuscated length: 11 bytes*)


(* ::Code:: *)
(*Prime@10001*)
